title: <p align="center"> Pritam Mukherjee </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="https://github.com/pritammukh">GitHub</a>

  <br>   
  I'm working on Data Engineering, Big Data, snowflake. Currently pursing AI and ML post graduation course.
  Also handing the ETL and ELT process in Data Analytics.
  Worked with Capgemini and accenture as a lead data engineer. 
  currently working in Siemens as IT Solution Expert.
  <br>
  </p>







theme: jekyll-theme-minimal
